### ISSUE TITLE
Move iceoryx-rs to eclipse-iceoryx

### ISSUE THREAD

**Issue by elBoberido** [elBoberido/iceoryx-rs#4]
To have this in a more prominent location and potentially speedup development, this should be move to https://github.com/eclipse-iceoryx/iceoryx-rs

**Comment by elBoberido** [comment]
@mossmaurice since you already created iceoryx-web, any hints what would be the best practice?

**Comment by mossmaurice** [comment]
@elBoberido It was the @eclipsewebmaster who created the repository. I suppose the best would be to open a Bugzilla ticket and ask the Eclipse team.
